name: klubradio_archivum
description: "Flutter app providing podcast-style access to the Klubrádió broadcast archive (https://www.klubradio.hu/archivum)."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  background_downloader: ^9.2.6
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.5
  http: ^1.2.2
  intl: any
  just_audio: any
  markdown_widget: ^2.3.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  xml: ^6.5.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: any
  change_app_package_name: ^1.2.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  intl_translation: any

flutter:
  uses-material-design: true
  generate: true # Enable intl code generation

  assets:
    - assets/legal/LEGAL.md
    - assets/app_icon/app_icon.png
    - assets/app_icon/app_icon_foreground.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/app_icon/app_icon.png
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF" # Brand color
  adaptive_icon_foreground: assets/app_icon/app_icon_foreground.png
  web:
    generate: true
    image_path: assets/app_icon/app_icon.png
    background_color: "#ffffff"
    theme_color: "#b00020" # Brand color
  windows:
    generate: true
    image_path: assets/app_icon/app_icon.png
  macos:
    generate: true
    image_path: assets/app_icon/app_icon.png
