name: klubradio_archivum
description: "Flutter app providing podcast-style access to the [Klubrádió Archive](https://www.klubradio.hu/archivum)."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.4

environment:
  sdk: ^3.9.2

dependencies:
  background_downloader: ^9.2.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  drift: ^2.29.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  http: ^1.5.0
  image: ^4.5.4
  intl: ^0.20.2
  just_audio: ^0.10.5
  just_audio_windows: ^0.2.2
  markdown_widget: ^2.3.2+8
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.40
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  xml: ^6.6.1

dev_dependencies:
  build_runner: ^2.9.0
  change_app_package_name: ^1.5.0
  drift_dev: ^2.29.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl_translation: ^0.21.0

flutter:
  uses-material-design: true
  generate: true # Enable intl code generation

  assets:
    - assets/legal/LEGAL.md
    - assets/api/response.json
    - assets/app_icon/app_icon.png
    - assets/app_icon/app_icon_foreground.png
    - assets/data/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/app_icon/app_icon.png
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF" # Brand color
  adaptive_icon_foreground: assets/app_icon/app_icon_foreground.png
  web:
    generate: true
    image_path: assets/app_icon/app_icon.png
    background_color: "#ffffff"
    theme_color: "#b00020" # Brand color
  windows:
    generate: true
    image_path: assets/app_icon/app_icon.png
  macos:
    generate: true
    image_path: assets/app_icon/app_icon.png
